#!/bin/bash

LOG="/tmp/eco_schedule.log"
echo "[$(date)] Script start" >> $LOG

SCHEDULE_FILE="/www/webUI/config/eco_schedule"
SCHEDULE_DIR="$(dirname "$SCHEDULE_FILE")"

read POSTDATA
echo "[$(date)] POST: $POSTDATA" >> $LOG

if [ ! -d "$SCHEDULE_DIR" ]; then
    mkdir -p "$SCHEDULE_DIR"
    touch "$SCHEDULE_DIR"
fi

if [ ! -f "$SCHEDULE_FILE" ]; then
    echo "[]" > "$SCHEDULE_FILE"
fi

EXISTING="$(cat "$SCHEDULE_FILE")"

# Parse action and id from POST data
action=$(echo "$POSTDATA" | jsonfilter -e '@.action' 2>/dev/null)
id=$(echo "$POSTDATA" | jsonfilter -e '@.id' 2>/dev/null)

# Default action is 'save' if not specified
[ -z "$action" ] && action="save"

echo "[$(date)] Action=$action, ID=$id" >> $LOG

convertTime() {
    local hour="$1"
    local min="$2"
    local ampm="$3"
    
    echo "[$(date)] convertTime: hour='$hour' min='$min' ampm='$ampm'" >> $LOG
    
    # Remove any leading zeros that might cause octal interpretation
    hour=$(echo "$hour" | sed 's/^0*//')
    min=$(echo "$min" | sed 's/^0*//')
    
    # Handle empty values
    [ -z "$hour" ] && hour=0
    [ -z "$min" ] && min=0
    
    # Convert to integers
    hour=$((hour))
    min=$((min))
    
    # Handle AM/PM conversion
    if [ "$ampm" = "PM" ] && [ "$hour" -lt 12 ]; then
        hour=$((hour + 12))
    elif [ "$ampm" = "AM" ] && [ "$hour" -eq 12 ]; then
        hour=0
    fi
    
    # Ensure hour is between 0-23
    hour=$((hour % 24))
    
    printf "%02d:%02d" "$hour" "$min"
}

# Function to rebuild cron from schedule file
rebuildCron() {
    local scheduleData="$1"
    
    cronFile="/etc/crontabs/root"
    tmpCron="/tmp/cron.new"
    existingCron="/tmp/cron.existing"
    
    # Clear temp files
    > $tmpCron
    > $existingCron
    
    # Preserve existing non-wireless cron entries if cron file exists
    if [ -f "$cronFile" ]; then
        # Copy existing cron but remove ALL wireless schedule related lines
        awk '
        /^# Generated by wireless_schedule.sh/ { skip=1; next }
        /^# DO NOT EDIT MANUALLY/ && skip { next }
        /eco_mode_control.sh/ { next }
        /^$/ && skip { skip=0; next }
        !skip { print }
        ' "$cronFile" > "$existingCron"
    fi
    
    # Start building new cron file with existing entries
    cat "$existingCron" > $tmpCron
    
    # Add wireless schedule section header
    echo "" >> $tmpCron
    echo "# Generated by wireless_schedule.sh" >> $tmpCron
    echo "# DO NOT EDIT MANUALLY" >> $tmpCron
    echo "" >> $tmpCron

    # Count total schedules
    total=0
    i=0
    while [ "$i" -lt 100 ]; do
        testId=$(echo "$scheduleData" | jsonfilter -e "@[$i].id" 2>/dev/null)
        if [ -z "$testId" ]; then
            break
        fi
        total=$((total + 1))
        i=$((i+1))
    done

    echo "[$(date)] Processing $total schedule entries for cron" >> $LOG

    index=0
    while [ "$index" -lt "$total" ]; do
        block=$(echo "$scheduleData" | jsonfilter -e "@[$index]" 2>/dev/null)
        eId=$(echo "$block" | jsonfilter -e '@.id' 2>/dev/null)
        eOffHr=$(echo "$block" | jsonfilter -e '@.offHour' 2>/dev/null)
        eOffMin=$(echo "$block" | jsonfilter -e '@.offMinute' 2>/dev/null)
        eOffAP=$(echo "$block" | jsonfilter -e '@.offAP' 2>/dev/null)
        eOnHr=$(echo "$block" | jsonfilter -e '@.onHour' 2>/dev/null)
        eOnMin=$(echo "$block" | jsonfilter -e '@.onMinute' 2>/dev/null)
        eOnAP=$(echo "$block" | jsonfilter -e '@.onAP' 2>/dev/null)

        echo "[$(date)] Processing entry $index: ID=$eId" >> $LOG

        cronOff=$(convertTime "$eOffHr" "$eOffMin" "$eOffAP")
        cronOn=$(convertTime "$eOnHr" "$eOnMin" "$eOnAP")

        coffHr=${cronOff%:*}
        coffMin=${cronOff#*:}
        cOnHr=${cronOn%:*}
        cOnMin=${cronOn#*:}

        # Get repeat days by iterating until empty
        j=0
        dayList=""
        while [ "$j" -lt 20 ]; do
            day=$(echo "$block" | jsonfilter -e "@.repeatDays[$j]" 2>/dev/null)
            if [ -z "$day" ]; then
                break
            fi

            case "$day" in
                Su) dayList="$dayList,0";;
                M) dayList="$dayList,1";;
                Tu) dayList="$dayList,2";;
                W) dayList="$dayList,3";;
                Th) dayList="$dayList,4";;
                F) dayList="$dayList,5";;
                Sa) dayList="$dayList,6";;
            esac

            j=$((j+1))
        done

        # Remove leading comma and handle empty case
        dayList=$(echo "$dayList" | sed 's/^,//')
        if [ -z "$dayList" ]; then
            dayList="*"
            echo "[$(date)] WARNING: No repeat days found for entry $eId, using '*'" >> $LOG
        fi

        echo "[$(date)] Entry $eId: days=$dayList, off=$coffMin $coffHr, on=$cOnMin $cOnHr" >> $LOG
        echo "$coffMin $coffHr * * $dayList /usr/bin/eco_mode_control.sh normal # $eId-off" >> $tmpCron
        echo "$cOnMin $cOnHr * * $dayList /usr/bin/eco_mode_control.sh eco # $eId-on" >> $tmpCron

        index=$((index+1))
    done

    echo "[$(date)] Cron file contents:" >> $LOG
    cat $tmpCron >> $LOG

    mv $tmpCron $cronFile
    /etc/init.d/cron restart >> $LOG 2>&1

    echo "[$(date)] Cron rebuilt and restarted." >> $LOG
}

# Handle actions based on the action parameter
if [ "$action" = "delete" ]; then
    # DELETE ACTION
    echo "[$(date)] DELETE action for ID=$id" >> $LOG
    
    if [ -z "$id" ]; then
        echo "Content-Type: application/json"
        echo ""
        echo "{\"status\":\"error\",\"message\":\"ID is required for delete action\"}"
        exit 1
    fi
    
    # Get count of existing schedules
    count=0
    i=0
    while [ "$i" -lt 100 ]; do
        oldId=$(echo "$EXISTING" | jsonfilter -e "@[$i].id" 2>/dev/null)
        if [ -z "$oldId" ]; then
            break
        fi
        count=$((count + 1))
        i=$((i+1))
    done
    
    # Build new list without the deleted entry
    updatedList="["
    found=0
    n=0
    
    while [ "$n" -lt "$count" ]; do
        oldId=$(echo "$EXISTING" | jsonfilter -e "@[$n].id" 2>/dev/null)
        obj=$(echo "$EXISTING" | jsonfilter -e "@[$n]" 2>/dev/null)
        
        if [ "$oldId" = "$id" ]; then
            found=1
            echo "[$(date)] Deleted entry with ID=$id" >> $LOG
        else
            updatedList="${updatedList}${obj},"
        fi
        
        n=$((n+1))
    done
    
    updatedList=$(echo "$updatedList" | sed 's/,$//')
    updatedList="${updatedList}]"
    
    if [ "$found" -eq 0 ]; then
        echo "[$(date)] WARNING: ID=$id not found for deletion" >> $LOG
        echo "Content-Type: application/json"
        echo ""
        echo "{\"status\":\"error\",\"message\":\"Schedule entry not found\"}"
        exit 1
    fi
    
    # Backup and save
    cp "$SCHEDULE_FILE" "$SCHEDULE_FILE.bak" 2>/dev/null
    echo "$updatedList" > "$SCHEDULE_FILE"
    echo "[$(date)] Updated schedule file saved after deletion." >> $LOG
    
    # Rebuild cron
    rebuildCron "$updatedList"
    
    echo "Content-Type: application/json"
    echo ""
    echo "{\"status\":\"ok\",\"message\":\"Schedule deleted successfully\"}"
    exit 0
fi

# Handle SAVE action (default for anything not 'delete')
if [ "$action" = "save" ]; then
    # SAVE ACTION
    echo "[$(date)] SAVE action for ID=$id" >> $LOG
    
    inc2g=$(echo "$POSTDATA" | jsonfilter -e '@.inc2g' 2>/dev/null)
    inc5g=$(echo "$POSTDATA" | jsonfilter -e '@.inc5g' 2>/dev/null)
    offHr=$(echo "$POSTDATA" | jsonfilter -e '@.offHour' 2>/dev/null)
    offMin=$(echo "$POSTDATA" | jsonfilter -e '@.offMinute' 2>/dev/null)
    offAP=$(echo "$POSTDATA" | jsonfilter -e '@.offAP' 2>/dev/null)
    onHr=$(echo "$POSTDATA" | jsonfilter -e '@.onHour' 2>/dev/null)
    onMin=$(echo "$POSTDATA" | jsonfilter -e '@.onMinute' 2>/dev/null)
    onAP=$(echo "$POSTDATA" | jsonfilter -e '@.onAP' 2>/dev/null)

    # Get array elements - just try to extract them until we get empty
    repeatDays=""
    repeatCount=0
    i=0
    while [ "$i" -lt 20 ]; do
        D=$(echo "$POSTDATA" | jsonfilter -e "@.repeatDays[$i]" 2>/dev/null)
        if [ -z "$D" ]; then
            break
        fi
        repeatDays="$repeatDays $D"
        repeatCount=$((repeatCount + 1))
        i=$((i+1))
    done

    echo "[$(date)] Parsed ID=$id Repeat=[$repeatDays] RepeatCount=$repeatCount" >> $LOG

    on24=$(convertTime "$onHr" "$onMin" "$onAP")
    off24=$(convertTime "$offHr" "$offMin" "$offAP")

    echo "[$(date)] ON=$on24 OFF=$off24" >> $LOG

    # Get count of existing schedules
    count=0
    i=0
    while [ "$i" -lt 100 ]; do
        oldId=$(echo "$EXISTING" | jsonfilter -e "@[$i].id" 2>/dev/null)
        if [ -z "$oldId" ]; then
            break
        fi
        count=$((count + 1))
        i=$((i+1))
    done

    found=0
    updatedList="["

    n=0
    while [ "$n" -lt "$count" ]; do
        oldId=$(echo "$EXISTING" | jsonfilter -e "@[$n].id" 2>/dev/null)
        obj=$(echo "$EXISTING" | jsonfilter -e "@[$n]" 2>/dev/null)

        if [ "$oldId" = "$id" ]; then
            found=1
            updatedList="${updatedList}${POSTDATA},"
            echo "[$(date)] Updated existing entry with ID=$id" >> $LOG
        else
            updatedList="${updatedList}${obj},"
        fi

        n=$((n+1))
    done

    if [ "$found" -eq 0 ]; then
        updatedList="${updatedList}${POSTDATA},"
        echo "[$(date)] Added new entry with ID=$id" >> $LOG
    fi

    updatedList=$(echo "$updatedList" | sed 's/,$//')
    updatedList="${updatedList}]"

    # Backup and save
    cp "$SCHEDULE_FILE" "$SCHEDULE_FILE.bak" 2>/dev/null

    echo "$updatedList" > "$SCHEDULE_FILE"
    echo "[$(date)] Updated schedule file saved." >> $LOG

    # Rebuild cron
    rebuildCron "$updatedList"

    # Output response
    echo "Content-Type: application/json"
    echo ""
    echo "{\"status\":\"ok\",\"message\":\"Schedule saved successfully\"}"
    exit 0
fi

# If we get here, unknown action
echo "[$(date)] ERROR: Unknown action=$action" >> $LOG
echo "Content-Type: application/json"
echo ""
echo "{\"status\":\"error\",\"message\":\"Unknown action: $action\"}"
exit 1