#!/bin/bash

LOG="/tmp/wireless_schedule.log"
echo "[$(date)] Script start" >> $LOG

SCHEDULE_FILE="/www/webUI/config/schedule"
SCHEDULE_DIR="$(dirname "$SCHEDULE_FILE")"

read POSTDATA
echo "[$(date)] POST: $POSTDATA" >> $LOG

if [ ! -d "$SCHEDULE_DIR" ]; then
    mkdir -p "$SCHEDULE_DIR"
    touch "$SCHEDULE_FILE"
fi

if [ ! -f "$SCHEDULE_FILE" ]; then
    echo "[]" > "$SCHEDULE_FILE"
fi

EXISTING="$(cat "$SCHEDULE_FILE")"

action=$(echo "$POSTDATA" | jsonfilter -e '@.action' 2>/dev/null)
id=$(echo "$POSTDATA" | jsonfilter -e '@.id' 2>/dev/null)

[ -z "$action" ] && action="save"

echo "[$(date)] Action=$action, ID=$id" >> $LOG

convertTime() {
    local hour="$1"
    local min="$2"
    local ampm="$3"
    
    echo "[$(date)] convertTime: hour='$hour' min='$min' ampm='$ampm'" >> $LOG
    
    hour=$(echo "$hour" | sed 's/^0*//')
    min=$(echo "$min" | sed 's/^0*//')
    
    [ -z "$hour" ] && hour=0
    [ -z "$min" ] && min=0
    
    hour=$((hour))
    min=$((min))
    
    if [ "$ampm" = "PM" ] && [ "$hour" -lt 12 ]; then
        hour=$((hour + 12))
    elif [ "$ampm" = "AM" ] && [ "$hour" -eq 12 ]; then
        hour=0
    fi
    
    hour=$((hour % 24))

    printf "%02d:%02d" "$hour" "$min"
}

# Parses a combined "H:MM AM/PM" string (the format offTime/onTime are
# always stored in) into 24-hour "HH:MM" via convertTime.
parseTimeStr() {
    local timeStr="$1"
    local hm="${timeStr%% *}"
    local ampm="${timeStr##* }"
    local hour="${hm%%:*}"
    local min="${hm##*:}"

    convertTime "$hour" "$min" "$ampm"
}

rebuildCron() {
    local scheduleData="$1"
    
    cronFile="/etc/crontabs/root"
    tmpCron="/tmp/cron.new"
    existingCron="/tmp/cron.existing"
    
    > $tmpCron
    > $existingCron
    
    if [ -f "$cronFile" ]; then
        awk '
        /^# Generated by wireless_schedule.sh/ { skip=1; next }
        /^# DO NOT EDIT MANUALLY/ && skip { next }
        /wifi_ap_control.sh/ { next }
        /^$/ && skip { skip=0; next }
        !skip { print }
        ' "$cronFile" > "$existingCron"
    fi
    
    cat "$existingCron" > $tmpCron
    
    echo "" >> $tmpCron
    echo "# Generated by wireless_schedule.sh" >> $tmpCron
    echo "# DO NOT EDIT MANUALLY" >> $tmpCron
    echo "" >> $tmpCron

    total=0
    i=0
    while [ "$i" -lt 100 ]; do
        testId=$(echo "$scheduleData" | jsonfilter -e "@[$i].id" 2>/dev/null)
        if [ -z "$testId" ]; then
            break
        fi
        total=$((total + 1))
        i=$((i+1))
    done

    echo "[$(date)] Processing $total schedule entries for cron" >> $LOG

    index=0
    while [ "$index" -lt "$total" ]; do
        block=$(echo "$scheduleData" | jsonfilter -e "@[$index]" 2>/dev/null)
        eId=$(echo "$block" | jsonfilter -e '@.id' 2>/dev/null)
        eOffTime=$(echo "$block" | jsonfilter -e '@.offTime' 2>/dev/null)
        eOnTime=$(echo "$block" | jsonfilter -e '@.onTime' 2>/dev/null)

        echo "[$(date)] Processing entry $index: ID=$eId" >> $LOG

        cronOff=$(parseTimeStr "$eOffTime")
        cronOn=$(parseTimeStr "$eOnTime")

        coffHr=${cronOff%:*}
        coffMin=${cronOff#*:}
        cOnHr=${cronOn%:*}
        cOnMin=${cronOn#*:}

        j=0
        dayList=""
        while [ "$j" -lt 20 ]; do
            day=$(echo "$block" | jsonfilter -e "@.repeatDays[$j]" 2>/dev/null)
            if [ -z "$day" ]; then
                break
            fi

            case "$day" in
                Su) dayList="$dayList,0";;
                M) dayList="$dayList,1";;
                Tu) dayList="$dayList,2";;
                W) dayList="$dayList,3";;
                Th) dayList="$dayList,4";;
                F) dayList="$dayList,5";;
                Sa) dayList="$dayList,6";;
            esac

            j=$((j+1))
        done

        dayList=$(echo "$dayList" | sed 's/^,//')
        if [ -z "$dayList" ]; then
            dayList="*"
            echo "[$(date)] WARNING: No repeat days found for entry $eId, using '*'" >> $LOG
        fi

        echo "[$(date)] Entry $eId: days=$dayList, off=$coffMin $coffHr, on=$cOnMin $cOnHr" >> $LOG
        echo "$coffMin $coffHr * * $dayList /usr/bin/wifi_ap_control.sh disable # $eId-off" >> $tmpCron
        echo "$cOnMin $cOnHr * * $dayList /usr/bin/wifi_ap_control.sh enable # $eId-on" >> $tmpCron

        index=$((index+1))
    done

    echo "[$(date)] Cron file contents:" >> $LOG
    cat $tmpCron >> $LOG

    mv $tmpCron $cronFile
    /etc/init.d/cron restart >> $LOG 2>&1

    echo "[$(date)] Cron rebuilt and restarted." >> $LOG
}


if [ "$action" = "delete" ]; then
    echo "[$(date)] DELETE action for ID=$id" >> $LOG
    
    if [ -z "$id" ]; then
        echo "Content-Type: application/json"
        echo ""
        echo "{\"status\":\"error\",\"message\":\"ID is required for delete action\"}"
        exit 1
    fi
    
    count=0
    i=0
    while [ "$i" -lt 100 ]; do
        oldId=$(echo "$EXISTING" | jsonfilter -e "@[$i].id" 2>/dev/null)
        if [ -z "$oldId" ]; then
            break
        fi
        count=$((count + 1))
        i=$((i+1))
    done
    
    updatedList="["
    found=0
    n=0
    
    while [ "$n" -lt "$count" ]; do
        oldId=$(echo "$EXISTING" | jsonfilter -e "@[$n].id" 2>/dev/null)
        obj=$(echo "$EXISTING" | jsonfilter -e "@[$n]" 2>/dev/null)
        
        if [ "$oldId" = "$id" ]; then
            found=1
            echo "[$(date)] Deleted entry with ID=$id" >> $LOG
        else
            updatedList="${updatedList}${obj},"
        fi
        
        n=$((n+1))
    done
    
    updatedList=$(echo "$updatedList" | sed 's/,$//')
    updatedList="${updatedList}]"
    
    if [ "$found" -eq 0 ]; then
        echo "[$(date)] WARNING: ID=$id not found for deletion" >> $LOG
        echo "Content-Type: application/json"
        echo ""
        echo "{\"status\":\"error\",\"message\":\"Schedule entry not found\"}"
        exit 1
    fi
    
    cp "$SCHEDULE_FILE" "$SCHEDULE_FILE.bak" 2>/dev/null
    echo "$updatedList" > "$SCHEDULE_FILE"
    echo "[$(date)] Updated schedule file saved after deletion." >> $LOG
    
    rebuildCron "$updatedList"
    
    echo "Content-Type: application/json"
    echo ""
    echo "{\"status\":\"ok\",\"message\":\"Schedule deleted successfully\"}"
    exit 0
fi

if [ "$action" = "save" ]; then
    # SAVE ACTION
    echo "[$(date)] SAVE action for ID=$id" >> $LOG
    
    inc2g=$(echo "$POSTDATA" | jsonfilter -e '@.inc2g' 2>/dev/null)
    inc5g=$(echo "$POSTDATA" | jsonfilter -e '@.inc5g' 2>/dev/null)
    offTimeStr=$(echo "$POSTDATA" | jsonfilter -e '@.offTime' 2>/dev/null)
    onTimeStr=$(echo "$POSTDATA" | jsonfilter -e '@.onTime' 2>/dev/null)

    repeatDays=""
    repeatCount=0
    i=0
    while [ "$i" -lt 20 ]; do
        D=$(echo "$POSTDATA" | jsonfilter -e "@.repeatDays[$i]" 2>/dev/null)
        if [ -z "$D" ]; then
            break
        fi
        repeatDays="$repeatDays $D"
        repeatCount=$((repeatCount + 1))
        i=$((i+1))
    done

    echo "[$(date)] Parsed ID=$id Repeat=[$repeatDays] RepeatCount=$repeatCount" >> $LOG

    on24=$(parseTimeStr "$onTimeStr")
    off24=$(parseTimeStr "$offTimeStr")

    echo "[$(date)] ON=$on24 OFF=$off24" >> $LOG

    count=0
    i=0
    while [ "$i" -lt 100 ]; do
        oldId=$(echo "$EXISTING" | jsonfilter -e "@[$i].id" 2>/dev/null)
        if [ -z "$oldId" ]; then
            break
        fi
        count=$((count + 1))
        i=$((i+1))
    done

    found=0
    updatedList="["

    n=0
    while [ "$n" -lt "$count" ]; do
        oldId=$(echo "$EXISTING" | jsonfilter -e "@[$n].id" 2>/dev/null)
        obj=$(echo "$EXISTING" | jsonfilter -e "@[$n]" 2>/dev/null)

        if [ "$oldId" = "$id" ]; then
            found=1
            updatedList="${updatedList}${POSTDATA},"
            echo "[$(date)] Updated existing entry with ID=$id" >> $LOG
        else
            updatedList="${updatedList}${obj},"
        fi

        n=$((n+1))
    done

    if [ "$found" -eq 0 ]; then
        updatedList="${updatedList}${POSTDATA},"
        echo "[$(date)] Added new entry with ID=$id" >> $LOG
    fi

    updatedList=$(echo "$updatedList" | sed 's/,$//')
    updatedList="${updatedList}]"

    cp "$SCHEDULE_FILE" "$SCHEDULE_FILE.bak" 2>/dev/null

    echo "$updatedList" > "$SCHEDULE_FILE"
    echo "[$(date)] Updated schedule file saved." >> $LOG

    rebuildCron "$updatedList"

    echo "Content-Type: application/json"
    echo ""
    echo "{\"status\":\"ok\",\"message\":\"Schedule saved successfully\"}"
    exit 0
fi

echo "[$(date)] ERROR: Unknown action=$action" >> $LOG
echo "Content-Type: application/json"
echo ""
echo "{\"status\":\"error\",\"message\":\"Unknown action: $action\"}"
exit 1